name: deploy order order-backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout github
        uses: actions/checkout@v4

      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.9"

      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: ap-northeast-2

      - name: update cluster information
        run: aws eks update-kubeconfig --name soldesk-eks --region ap-northeast-2

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Gateway 빌드
      - name: gateway build and push docker image to ecr
        env:
          REGISTRY: 446100759833.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: apigateway
          IMAGE_TAG: latest
        run: |
          docker build \
            -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
            -f ./msa/apigateway/Dockerfile ./msa/apigateway
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: deploy gateway
        run: |
          kubectl apply -f ./msa/apigateway/k8s/depl_svc.yml
          kubectl rollout restart deployment apigateway-depl -n soldesk


      # Member 빌드
      - name: member build and push docker image to ecr
        env:
          REGISTRY: 446100759833.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: member-service
          IMAGE_TAG: latest
        run: |
          docker build \
            -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
            -f ./msa/member/Dockerfile ./msa/member
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: deploy member
        run: |
          kubectl apply -f ./msa/member/k8s/depl_svc.yml
          kubectl rollout restart deployment member-depl -n soldesk


      # Ordering 빌드
      - name: order build and push docker image to ecr
        env:
          REGISTRY: 446100759833.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: ordering-service
          IMAGE_TAG: latest
        run: |
          docker build \
            -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
            -f ./msa/ordering/Dockerfile ./msa/ordering
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: deploy ordering
        run: |
          kubectl apply -f ./msa/ordering/k8s/depl_svc.yml
          kubectl rollout restart deployment ordering-depl -n soldesk


      # Product 빌드
      - name: product build and push docker image to ecr
        env:
          REGISTRY: 446100759833.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: product-service
          IMAGE_TAG: latest
        run: |
          docker build \
            -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
            -f ./msa/product/Dockerfile ./msa/product
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: deploy product
        run: |
          kubectl apply -f ./msa/product/k8s/depl_svc.yml
          kubectl rollout restart deployment product-depl -n soldesk